global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: "mlops_inference_ec2"
    metrics_path: /metrics
    honor_timestamps: false
    static_configs:
      - targets: ["16.170.148.255:8000"]
        labels:
          service: "mlops-inference"
          environment: "production"
  - job_name: "mlops_inference_local"
    metrics_path: /metrics
    honor_timestamps: false
    static_configs:
      - targets: ["inference:8000"]
        labels:
          service: "mlops-inference"
          environment: "local"
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
